'use client';
import { motion } from 'framer-motion';
import {ArrowRight,BriefcaseBusiness,Building2,Check,GraduationCap,HeartHandshake,Mail,MapPin,Phone,Target,UserPlus,Users} from 'lucide-react';

import SiteHeader from '../components/SiteHeader';
const S=[['Executive Search','Identify and attract senior leaders who can shape your organisation’s future.',Users],['Recruitment & Staffing','Find the right talent faster with a structured, scalable hiring process.',UserPlus],['HR Consulting','Build people strategies, processes, and organisational structures that last.',BriefcaseBusiness],['Leadership Development','Develop stronger managers and future-ready leaders.',GraduationCap],['Employee Engagement','Create cultures where people perform, collaborate, and grow.',HeartHandshake],['Talent Strategy','Align your workforce strategy with long-term business objectives.',Target]];
const I=['Technology','BFSI','Healthcare','Manufacturing','Retail & E-commerce','Education','Real Estate','Professional Services']; const img='https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85';
export default function Home(){return <main><SiteHeader active="home"/>
<section id="home" className="relative overflow-hidden bg-[#F7F9FC] py-16 lg:py-24"><div className="absolute right-0 top-0 h-full w-2/5 bg-[#e7f4f3]"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}}><p className="eyebrow">HR CONSULTING · TALENT · GROWTH</p><h1 className="mt-6 text-5xl font-bold leading-[1.05] tracking-[-.045em] text-[#0B1F33] sm:text-6xl">Building better teams.<br/><span className="text-[#2457A6]">Driving better business.</span></h1><p className="copy">We help organisations attract exceptional talent, build high-performing teams, and create people strategies that drive sustainable business growth.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#services" className="btn bg-[#0B1F33] text-white">Explore Our Services <ArrowRight size={17}/></a><a href="#contact" className="btn border border-slate-300 bg-white">Talk to an HR Expert</a></div><div className="mt-10 flex gap-7 border-t pt-5 text-sm">{[['10+','Years experience'],['500+','Placements'],['50+','Clients']].map(x=><span key={x[0]}><b className="block text-xl">{x[0]}</b>{x[1]}</span>)}</div></motion.div><motion.div initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} className="relative"><img src={img} alt="Consultants collaborating" className="h-[500px] w-full rounded-2xl object-cover shadow-2xl"/><motion.div animate={{y:[0,-10,0]}} transition={{repeat:Infinity,duration:3}} className="absolute -bottom-6 -left-5 rounded-xl bg-white p-5 shadow-xl"><b className="text-3xl text-[#2457A6]">500+</b><span className="ml-3 text-sm">Successful<br/>placements</span></motion.div></motion.div></div></section>
<section className="mx-auto max-w-7xl px-6 py-10 text-center"><p className="eyebrow text-slate-400">TRUSTED BY GROWING ORGANISATIONS</p><div className="mt-6 flex flex-wrap justify-center gap-x-12 gap-y-4 font-semibold tracking-[.12em] text-slate-400">{['NEXORA','VERTEX','NORTHSTAR','AURORA','INFINEX','CREDOVA'].map(x=><span key={x}>{x}</span>)}</div></section>
<section id="about" className="mx-auto grid max-w-7xl gap-14 px-6 py-24 lg:grid-cols-2"><img src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=85" alt="Business team meeting" className="h-[420px] w-full rounded-2xl object-cover"/><div className="self-center"><p className="eyebrow">WHO WE ARE</p><h2>People strategy that creates business impact.</h2><p className="copy">We partner with organisations to solve their most important people challenges—from finding exceptional talent to building stronger leadership teams and scalable HR strategies.</p><ul className="mt-7 grid gap-4 sm:grid-cols-2">{['Experienced consultants','Industry-focused expertise','Data-driven approach','Long-term partnerships'].map(x=><li className="flex gap-2 font-medium" key={x}><Check className="text-[#16A6A3]" size={18}/>{x}</li>)}</ul></div></section>
<section id="services" className="bg-[#F7F9FC] py-24"><div className="mx-auto max-w-7xl px-6"><p className="eyebrow">WHAT WE DO</p><h2>Our HR & Talent Solutions</h2><p className="copy">End-to-end people solutions designed around your business goals.</p><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{S.map(([t,d,Icon])=>{const C=Icon as typeof Users;return <motion.article whileHover={{y:-6}} className="group rounded-2xl border bg-white p-7 shadow-sm" key={t as string}><C className="mb-7 text-[#2457A6]" size={30}/><h3>{t as string}</h3><p className="mt-3 leading-7 text-slate-600">{d as string}</p><ArrowRight className="mt-6 text-[#16A6A3]" size={19}/></motion.article>})}</div></div></section>
<section className="bg-[#0B1F33] py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2"><div><p className="eyebrow text-[#61cfcc]">THE TALENTBRIDGE DIFFERENCE</p><h2 className="text-white">Why organisations choose us.</h2><p className="mt-6 leading-8 text-slate-300">Human insight and disciplined process, brought together to make every people decision count.</p></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl bg-white/15">{[['500+','Successful Placements'],['50+','Corporate Clients'],['10+','Years of Expertise'],['95%','Client Satisfaction']].map(x=><div className="bg-[#102942] p-9" key={x[0]}><b className="text-4xl text-[#61cfcc]">{x[0]}</b><p className="mt-3 text-slate-300">{x[1]}</p></div>)}</div></div></section>
<section id="industries" className="mx-auto max-w-7xl px-6 py-24"><p className="eyebrow">SECTOR EXPERTISE</p><h2>Industries we serve.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{I.map(x=><a href="#contact" className="flex items-center gap-3 rounded-xl border p-5 font-semibold hover:border-[#16A6A3]" key={x}><Building2 size={19} className="text-[#2457A6]"/>{x}</a>)}</div></section>
<section id="careers" className="mx-auto grid max-w-7xl gap-8 px-6 py-12 lg:grid-cols-2"><div className="rounded-2xl bg-[#e8f5f4] p-10"><p className="eyebrow">FOR CANDIDATES</p><h2>Looking for your next opportunity?</h2><p className="copy">Connect with our recruitment specialists and discover opportunities aligned with your skills, experience, and career goals.</p><a href="#contact" className="btn mt-7 bg-[#0B1F33] text-white">Explore Careers <ArrowRight size={17}/></a></div><div className="rounded-2xl bg-[#2457A6] p-10 text-white"><p className="eyebrow text-[#a8e8e6]">FOR EMPLOYERS</p><h2 className="text-white">Need exceptional talent?</h2><p className="mt-5 text-lg text-blue-100">Let’s build the team that moves your business forward.</p><a href="#contact" className="btn mt-8 bg-white text-[#0B1F33]">Hire With Us <ArrowRight size={17}/></a></div></section>
<section id="insights" className="bg-[#F7F9FC] py-24"><div className="mx-auto max-w-7xl px-6"><p className="eyebrow">OUR PERSPECTIVE</p><h2>Insights that move businesses forward.</h2><div className="mt-10 grid gap-6 md:grid-cols-3">{[['The Future of Talent Acquisition','How modern organisations attract and retain talent.'],['Building High-Performance Teams','Practical strategies for collaborative teams.'],['Leadership Trends','What future leaders need to consider.']].map(x=><article className="rounded-2xl bg-white p-7 shadow-sm" key={x[0]}><p className="eyebrow">INSIGHTS · 12 MIN READ</p><h3 className="mt-4">{x[0]}</h3><p className="mt-3 text-slate-600">{x[1]}</p><a href="#contact" className="mt-6 inline-flex gap-2 font-bold text-[#2457A6]">Read Article <ArrowRight size={17}/></a></article>)}</div></div></section>
<section id="contact" className="bg-[#0B1F33] py-24 text-white"><div className="mx-auto max-w-7xl px-6"><div><p className="eyebrow text-[#61cfcc]">START A CONVERSATION</p><h2 className="text-white">Let’s build your people strategy.</h2><p className="mt-6 leading-8 text-slate-300">Whether you’re looking for exceptional talent or a stronger HR function, our team is ready to help.</p><div className="mt-8 space-y-4 text-slate-200"><p className="flex gap-3"><Phone size={19}/>+91 22 4102 8890</p><p className="flex gap-3"><Mail size={19}/>hello@talentbridge.co</p><p className="flex gap-3"><MapPin size={19}/>BKC, Mumbai · Mon–Fri</p></div></div></div></section></main>}
